### ISSUE TITLE
Library not available in Arduino Library Manager

### ISSUE THREAD

**Issue by sai-ydev** [adafruit/Adafruit_AGS02MA#2]
This library is not available under Arduino Library Manager. I searched locally both on my IDE and the Arduino Library List. It is missing.

Also, the picture of the sensor in ReadMe needs to be corrected. It shows a picture of an HTS221 sensor.

**Comment by tyeth** [comment]
This issue should now be resolved :)
![image](https://github.com/adafruit/Adafruit_AGS02MA/assets/6692083/24497255-910c-472b-80c3-ce8457d4bcc0)
